### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by medas** [google-developer-training/android-basics-kotlin-mars-photos-app#10]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5

**In which task and step of the codelab can this issue be found?**
Assign the result we just received from the backend server to the _status.value.

 val listResult = MarsApi.retrofitService.getProperties()
 _status.value = listResult

**Describe the problem**
the getProperties should be replaced by getPhotos

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jhansitavva** [comment]
@medas 
Thank you so much for reporting this issue. This is fixed and will be published soon.
