### ISSUE TITLE
Android Basics: Coroutines

### ISSUE THREAD

**Issue by ratneshnavlakhe** [google-developer-training/android-basics-kotlin-mars-photos-app#101]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-introduction-coroutines?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-introduction-coroutines#5

**In which task and step of the codelab can this issue be found?**
6

**Describe the problem**
The program doesn't output all the threads.

**Solution**
After removing the delay(5000) from the code it works.

**Steps to reproduce?**
1. Copy the code snippet
2. Go on https://developer.android.com/training/kotlinplayground and paste and run.
3. It doesn't output all the threads.

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@ratneshnavlakhe 
Thank you for reaching out to us. We took your suggestion to remove the line `delay(5000)` into consideration and updated the codelab code snippet. 
![Screen Shot 2022-04-15 at 11 42 52 AM](https://user-images.githubusercontent.com/86437155/163608803-42a3400b-b6b6-43cf-9ebc-e755ac6606fa.png)
It will be published soon.
