### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by Bjastkuliar** [google-developer-training/android-basics-kotlin-mars-photos-app#109]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
[link](https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images)

**In which task and step of the codelab can this issue be found?**

3

**Describe the problem**

The list of repositories should have jcenter removed

**Steps to reproduce?**
1. Go to[link] (https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images#2)
3. See error in the image just above section "Update View Model"

**Versions**
_Android Studio version:_ 2023.1
_API version of the emulator:_ 31 (Real device)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Cattura](https://user-images.githubusercontent.com/61975472/145564974-22a089bc-117a-4729-b7bc-6c2b6c7a2325.PNG)

**Comment by osuleymanova** [comment]
@Bjastkuliar 
Thank you for reaching out to us. It looks like the issue was fixed:
![Screen Shot 2022-04-12 at 5 25 00 PM](https://user-images.githubusercontent.com/86437155/163075506-afbc8f83-af1f-4838-9a8e-89e2a27be2a3.png)
