### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by lossrodrigo** [google-developer-training/android-basics-kotlin-mars-photos-app#111]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: '6 - Connecting to te internet'
assignees: ''

---

**[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet#5)**

**In which task and step of the codelab can this issue be found?**
In ViewModelScope
Item 5. Assign the result we just received from the backend server to the _status.value.

**Describe the problem**

When you translate to portuguese you check a writing error in the sentence bellow:

Wrong sentence
val listResult = MarsApi.retrofitService.**getProperties()**
 _status.value = listResult

Right sentence
val listResult = MarsApi.retrofitService.**getPhotos()**
 _status.value = listResult

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@lossrodrigo 
Thank you for reaching out to us.  It looks like the localization issue has been already fixed:
![Screen Shot 2022-04-14 at 12 26 37 PM](https://user-images.githubusercontent.com/86437155/163462397-8fea7379-161c-4703-8dad-1c3aba003500.png)
