### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by 3li-7assan-Dev1712** [google-developer-training/android-basics-kotlin-mars-photos-app#112]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#7

**In which task and step of the codelab can this issue be found?**
in the task of Add Moshi dependency

**Describe the problem**

It's a simple typo problem in the code, specifically in the comment it says: "// Retrofit with Moshi Converter"
it should be "// Retrofit with Scalars Converter"

**Steps to reproduce?**
1. Go to...
![Screenshot (242)](https://user-images.githubusercontent.com/83492333/146665045-e0a6c393-0780-4255-a7c9-8635b748a86d.png)

2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@3li-7assan-Dev1712 
Thank you for reaching out to us. Actually there is no typo: if you follow the steps provided in the codelab, it is said that the incorrect line should be replaced:
![Screen Shot 2022-04-14 at 12 08 41 PM](https://user-images.githubusercontent.com/86437155/163460298-3a77f532-23bb-4b0e-bc50-a34e195d0a8e.png)

**Comment by 3li-7assan-Dev1712** [comment]
Okay, now I understand. Thanks for the clarification.

**Comment by osuleymanova** [comment]
@3li-7assan-Dev1712 
Good! Most welcome!
