### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by WegenDerSucht** [google-developer-training/android-basics-kotlin-mars-photos-app#113]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#7

**In which task and step of the codelab can this issue be found?**
8 - Add Moshi library dependencies

**Describe the problem**
To be able to use the KotlinJsonAdapterFactory for the Moshi Builder you also need to add to the dependencies:  implementation 'com.squareup.moshi:moshi-kotlin:1.12.0'

**Steps to reproduce?**
just follow the guide

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@WegenDerSucht 
Thank you for reaching out to us. Actually it's added:
![Screen Shot 2022-04-14 at 12 01 28 PM](https://user-images.githubusercontent.com/86437155/163458735-016f1e20-e7c7-4a59-9af3-d2294b94489e.png)

The version in the code snippet will be updated (to 1.13.0) and published soon.
