### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by smish-hash** [google-developer-training/android-basics-kotlin-mars-photos-app#117]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-internet-images

**In which task and step of the codelab can this issue be found?**
This issue can be found in **Step 3** under the **Update the ViewModel section**

**Describe the problem**
In the section mentioned above, the screen of the emulator that is attached seems to be showing different data than what it mentions in the tutorial guide. The textview should be showing a URL, but instead, it is showing "Failure Message". If we look at it carefully, it can be clearly seen that the flight mode on the emulator is switched on, due to which the data doesn't update. I am uploading a screenshot that will make it easier to locate

**Versions**
_Android Studio version:_ All versions

**Additional information**
Screenshot
![image](https://user-images.githubusercontent.com/55646021/147956279-d572e157-bfc0-489b-9b13-0bd80a2f214a.png)

**Comment by osuleymanova** [comment]
@smish-hash 
Thank you for reaching out to us. The image was updated:
![Screen Shot 2022-04-12 at 2 45 40 PM](https://user-images.githubusercontent.com/86437155/163239321-02148e78-4876-45cb-adf5-c83ad0810d96.png)
