### ISSUE TITLE
Value for endpoint changed from "photos" to "photo" in the MarsApiService interface  shown in step 8

### ISSUE THREAD

**Issue by Elmohound** [google-developer-training/android-basics-kotlin-mars-photos-app#12]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#7

**In which task and step of the codelab can this issue be found?**
8. Parse the JSON response with Moshi,
Update MarsApiService and OverviewViewModel (step5)

**Describe the problem**
Here is the sample code snippet:

_interface MarsApiService {
   @GET("photo")
   fun getPhotos(): List<MarsPhoto>
}_

Problem 1: The endpoint should be "photos", otherwise a 404 error is occurs. 
Problem 2: Earlier in the codelab, this was a suspend function. It is not clear to the student (i.e. me) whether this change is intentional rather than a typographical error. 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Elmohound 
Thank you for reaching out to us. The issue is fixed and published.
