### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by nehem10** [google-developer-training/android-basics-kotlin-mars-photos-app#120]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#6

**In which task and step of the codelab can this issue be found?**
Android permissions 

**Describe the problem**
when adding <uses-permission android:name="android.permission.INTERNET" /> this to the manifests/AndroidManifest.xml , if you have already installed the app within the android emulator . Then after adding this attribute to the MANIFEST still you will get the error of java.net.SocketException: socket failed: EPERM (Operation not permitted).

It would be better if the documentation/ codelab specified the learner to first uninstall the app and then reinstall it . This would make the program work and the reason why is is necessary to re - install the app in the emulator. I found my fix by the above method, if there are any simpler fix we can specify that.  

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by tamarabuilds** [comment]
@nehem10 Thank you! This was exactly my same error. Your solution worked - much appreciated!

**Comment by nehem10** [comment]
> @nehem10 Thank you! This was exactly my same error. Your solution worked - much appreciated!

I am happy that I could help.
