### ISSUE TITLE
80% of work you are to told to do is allrady done.

### ISSUE THREAD

**Issue by weather-tracker** [google-developer-training/android-basics-kotlin-mars-photos-app#122]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit getting data from the internet codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

seems 80% of the steps you tell me to do are allrady done for me.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by wgoodey** [comment]
You can get to the intended starter code by opening the Git pane, right-clicking on the starter branch, and selecting checkout.

![git-checkout](https://user-images.githubusercontent.com/36968359/172235844-0eb8edcc-bebf-4343-ba25-8b5b9b028ce4.jpg)
