### ISSUE TITLE
Android Basics: Get data from the Internet - MoshiConverterFactory issues

### ISSUE THREAD

**Issue by ScottMal69** [google-developer-training/android-basics-kotlin-mars-photos-app#123]
---
name: Android Basics Unit 8 issue - Update MarsApiService and OverviewViewModel
about: Report problems with replacing ScalarsconverterFactory with MoshiConverterFactory
title: 'Android Basics Unit 8 issue: Update MarsApiService and OverviewViewModel'
labels: 'moshi, MoshiConverterFactory'
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet#7

**In which task and step of the codelab can this issue be found?**
Parse the JSON response with Moshi: Update MarsApiService and OverviewViewModel: Step #4

**Describe the problem**
Changing the Retrofit builder to use MoshiConverterFactory instead of the ScalarConverterFactory and pass in the moshi instance just created, get this message:  Unresolved reference: MosshiConverterFactory.  And when add the import retrofit2.converter.moshi.MoshiConverterFactory, get unresolved reference: moshi

**Steps to reproduce?**
1. Following along with the codelab in sequence
2. Unit 8:  Step 4:  
3. See screen shot:  below
4. Note, I cut and paste the code for the MarsApiService.kt file from your solution page.  Code is exactly like yours. 
5. I also closed Android Studio and opened it back up again, did a build...same issues!

**Versions**
_Android Studio version:_ Android Studio Bumblebee | 2021.1.1 Patch 2 (Build #AI-211.7628.21.2111.8193401)
_API version of the emulator:_ Pixel 3a XL API 30 - Android 11.0 Google APIs | x86
Kotlin: 211-1.6.10-release-923-AS7442.40

**Additional information**
![image](https://user-images.githubusercontent.com/94263443/158035280-b59efaef-54fd-4d22-9698-166ea427a86d.png)

**Comment by weather-tracker** [comment]
i think you have to leave it. also if you look at their code verses your the base url line on their gitgub only uses 1 line not 2 even though when they have you copy it it takes 2 lines on the computer.

all i ever figured out was if you do not modify anything it will compile and work.

**Comment by weather-tracker** [comment]
dont know why they said we will use moshi then do the work with scalers for you.
but the app they have you download dows use moshi.
here is for the file you are in.
https://github.com/google-developer-training/android-basics-kotlin-mars-photos-app/blob/main/app/src/main/java/com/example/android/marsphotos/network/MarsApiService.kt

**Comment by ScottMal69** [comment]
Thanks weather-tracker.  I cut-n-paste the Kotlin code from the file you provided a link to.  However, the problem still exists after doing a build.  I also closed out Android Studio and restarted and the problem still exists!

**Comment by tamarabuilds** [comment]
@ScottMal69 Have you confirmed that your gradle files are the same as the solution? That's one thing I've double-checked sometimes. Also, you have a typo in your screenshot, MosshiConverterFactory --> MoshiConverterFactory

**Comment by ScottMal69** [comment]
skatingtamara,
Thanks for the information.  I had already corrected the typo error.  Where would I find the build.gradle solution files?  I can only find the starter project files on github.   I would be glad to compare mine to them if I knew where they were.  Thanks again!

**Comment by tamarabuilds** [comment]
@ScottMal69, this took me a min to figure out as I'm a coding newbie but you can find the solution (if there is one) in the different branch of the GitHub codelab.

Select the test_solution branch on the left, then download that code and import it. Then you can compare the final solution with what you've got. 
![image](https://user-images.githubusercontent.com/98510821/160012600-c661990a-c63d-4695-8e80-1a51d8e43b2c.png)

I hope that helps!

**Comment by weather-tracker** [comment]
i am new also.
weird part is that all the work the say to do is done for at least me in the GitHub download main branch.
if you touch nothing and just run it it worked for me.

in the build.gradle file there is a dependency section, are all the dependencys in it.
 https://github.com/google-developer-training/android-basics-kotlin-mars-photos-app/blob/main/app/build.gradle

**Comment by ScottMal69** [comment]
Thanks to both skatingtamara and weather-tracker for help on this one.  Once I found the build.gradle file (thanks weather-tracker) I cut and paste the code and did a build...voila!  Worked perfectly.  And thanks for sharing the solution filter in githut (skatingtamara).  I really, really appreciate your help!  Thanks again!
