### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by Linex-code** [google-developer-training/android-basics-kotlin-mars-photos-app#124]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?hl=es&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%3Fhl%3Des%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#7

**In which task and step of the codelab can this issue be found?**
step 8

**Describe the problem**
In a sample code its says:
interface MarsApiService {
   @GET("photo")
   fun getPhotos(): List<MarsPhoto>
}

I think it need to add the 'suspend' before de function getPhotos()

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Linex-code 
Thank you for reaching out to us. 
You are absolutely right about 'suspend'. The code should look like this:
![Screen Shot 2022-04-14 at 11 53 23 AM](https://user-images.githubusercontent.com/86437155/163457605-8b484bb4-f2b4-4e0d-a8f5-c33888113032.png)
Happy coding!
