### ISSUE TITLE
Android Basics: Get data from the Internet/ CANNOT FIND UPDATE GRADLE LINE!

### ISSUE THREAD

**Issue by jh115424** [google-developer-training/android-basics-kotlin-mars-photos-app#125]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
CANNOT FIND UPDATED GRADLE LINE.   THE ONES IN GOT HUB ARE 4 MONTHS OLD AND NOT CORRECT ANYMORE!

THIS IS THE ONE LINE I COULD NOT UPDATE.

   **implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by spamshot** [comment]
This should be in your build.gradle (Project:name)
all the way at the top maybe about line 17 in buildscript.
your looking for kotlin_version = "1.6.20"
![screenshot0001](https://user-images.githubusercontent.com/3164403/162442115-c7c341d1-458d-46c6-8a32-438fea8d51bc.png)

**Comment by jh115424** [comment]
Ah!  Thanks so much!


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:5d71e744-55d7-412e-abca-8ac94779a8a3]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
ok, I put it in there but I get a red line at the end.

Screen shots below!

<img width="1440" alt="Screen Shot 2022-04-08 at 8 26 15 AM" src="https://user-images.githubusercontent.com/91148652/162445394-a2bb00ad-4fbf-4401-817f-074ecddff9c7.png">

<img width="1440" alt="Screen Shot 2022-04-02 at 7 21 07 AM" src="https://user-images.githubusercontent.com/91148652/162445423-e3171711-d2ce-4ff3-b2c6-a696926108f4.png">

**Comment by spamshot** [comment]
You have a type-o. you started with " but ended with '
change the end to "
![Untitled](https://user-images.githubusercontent.com/3164403/162460337-f0f7b126-cea5-4dd8-9b53-48965886833d.png)

**Comment by jh115424** [comment]
AH!   Yes, your right....thanks!


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:3cf4daf7-16d1-4558-a18b-1ca2d8fc8aff]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
can I see a screenshot of your gradles in the project app?


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:8da1863c-7a07-4ed2-b444-a7a926b9edc1]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
ok, I did that.

It did not work.

Screen shot in Github


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:2734b6d4-9153-4a96-9d68-ba874a9a5080]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
ok, when I tried to sync the grades, a different issue came up....

<img width="1440" alt="Screen Shot 2022-04-08 at 12 01 29 PM" src="https://user-images.githubusercontent.com/91148652/162488430-d446dec9-de46-448d-ad6e-65c1aacdd2e3.png">

It says the plugins are not found.

**Comment by spamshot** [comment]
How far are you in the marsPhotos app.
if you just started re-download the mars zip and just update the files.
or just try coping my code
```
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
}
```


```
dependencies {
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
    implementation 'androidx.core:core-ktx:1.7.0'

    //Navigation
    implementation 'androidx.navigation:navigation-fragment-ktx:2.4.2'
    implementation 'androidx.navigation:navigation-ui-ktx:2.4.2'

    implementation 'com.google.android.material:material:1.5.0'

    // Moshi
    implementation 'com.squareup.moshi:moshi-kotlin:1.9.3'

    // Retrofit with Moshi Converter
    implementation 'com.squareup.retrofit2:converter-moshi:2.9.0'

    // Coil
    implementation "io.coil-kt:coil:1.1.1"
    
}
```

Then inside the build.gradle Project
```
buildscript {
    ext {
        // Versions for all the dependencies we plan to use. It's particularly useful for kotlin
        // where the versions of the plugin needs to be the same as the version of the
        // library defined in the app Gradle file
        kotlin_version = "1.6.20"
    }
```
Then run the Migrations

**Comment by jh115424** [comment]
thanks so much!

I am just starting it.


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:ce0487a2-9ec8-404f-a4c0-064da1e93bba]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by osuleymanova** [comment]
@jh115424 
Are you still facing the errors? Please let us know and provide the screenshots so we could help you with troubleshooting.

**Comment by jh115424** [comment]
I sent a comment in Github of an error line


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:9635361f-3755-41ac-8715-3e86cd9b3a57]<https://your.tradeinvalet.com/tdhe0j>

________________________________
