### ISSUE TITLE
Android Basics: Get data from the Internet - Typo

### ISSUE THREAD

**Issue by jayarevee** [google-developer-training/android-basics-kotlin-mars-photos-app#128]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#4

**In which task and step of the codelab can this issue be found?**
Step 5 -[Web Services and Retrofit - Add Retrofit dependencies]

**Describe the problem**

Small type for the comment for the scalars dependcy 
```
// Retrofit with **Moshi** Converter
implementation "com.squareup.retrofit2:converter-scalars:2.9.0"
```
It says "Retrofit with Moshi Converter" but should be "Retrofit with Scalar Converter"
**Steps to reproduce?**

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@jayarevee 
Thank you for reaching out to us. The issue is fixed and will be published soon:
![Screen Shot 2022-05-09 at 4 46 18 PM](https://user-images.githubusercontent.com/86437155/167516057-44e332cd-fe9b-4bf8-abcd-c24807141af8.png)
