### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by cjgunzel** [google-developer-training/android-basics-kotlin-mars-photos-app#129]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
[332332](https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5)

**In which task and step of the codelab can this issue be found?**
step 6

**Describe the problem**
building the project per instructions it does not work -- errors

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...build the project on this page.  I skipped ahead to the "solution" code which, itself, does not work.

**Versions**
_Android Studio version:_ 2021.2
_API version of the emulator:_ most recent

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@samdutton 
Thank you for reaching out to us. Could you please provide the screenshots of the errors you have faced with?

**Comment by samdutton** [comment]
@osuleymanova When/where was this reported? I don't remember filing this bug (but it might have been ages ago!)

**Comment by osuleymanova** [comment]
@cjgunzel 
Thank you for reaching out to us. Could you please provide the screenshots of the errors you have faced with?
