### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by cjgunzel** [google-developer-training/android-basics-kotlin-mars-photos-app#130]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5

**In which task and step of the codelab can this issue be found?**
Step 6

**Describe the problem**
building the codelab at this page produces errors I have no idea how to fix.  I skipped to the "solution" code which does not eliminate the errors.  I thought I had reported this but the URL appeared to be a number so I'm resubmitting.   You may delete the other one without the URL.

**Steps to reproduce?**
1. Go to...the codelab
2. Click on...build up to step 6
3. See error...errors I don't know how to fix

**Versions**
_Android Studio version:_ 2021.1
_API version of the emulator:_ latest -- but I'm using my phone not the emulator

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@samdutton 
Thank you for reaching out to us and sharing your concerns. Please provide the screenshots of the errors you faced so we could help you with troubleshooting.

**Comment by samdutton** [comment]
When/how was this reported? I don't remember reporting this bug (though it may have been a long time ago!)
