### ISSUE TITLE
test_solution

### ISSUE THREAD

**Issue by Dianixy** [google-developer-training/android-basics-kotlin-mars-photos-app#132]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-test-network-request?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-test-network-request#7

**In which task and step of the codelab can this issue be found?**
Step 8

**Describe the problem**
Where is a test_solution?
In https://github.com/google-developer-training/android-basics-kotlin-mars-photos-app there are only main and starter.

**Comment by osuleymanova** [comment]
@Dianixy 
Thank you for reaching out to us.This codelab is deprecated and will be removed soon.
