### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by idongesit98** [google-developer-training/android-basics-kotlin-mars-photos-app#137]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**

**In which task and step of the codelab can this issue be found?**
Connecting to the internet

**Describe the problem**
it was showing internet permission denied
![debugger internet](https://user-images.githubusercontent.com/101020121/172718724-ef303c17-ff6f-435a-8d2d-63cf31c91bf1.png)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem.
![andoid manifest](https://user-images.githubusercontent.com/101020121/172718856-4ed2900a-cb2e-40e1-93e6-82e0a1e27be7.png)
![debugger internet](https://user-images.githubusercontent.com/101020121/172718900-6b88c129-10b4-48c5-aa46-c43ffe7ed512.png)
![debugger internet](https://user-images.githubusercontent.com/101020121/172718914-fda832cb-294d-4e44-9ccb-06df332a502f.png)
_

**Comment by xhbear** [comment]
You may have overlooked the setup process, go to your AndroidManifest file and add below permission.

```
<uses-permission android:name="android.permission.INTERNET"/>
```

Put above code withint the <manifest> </manifest> body:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.android.marsphotos">

    <uses-permission android:name="android.permission.INTERNET"/>

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        ...
    </application>

</manifest>
```

This is necessary when writing a program that needs access to the web.
Hope this helps!

**Comment by osuleymanova** [comment]
@idongesit98 
Thank you for reaching out to us. Please let us know if you still face the same issue.
