### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by alejopp** [google-developer-training/android-basics-kotlin-mars-photos-app#139]
---
name: Android Basics Unit 6 issue
about: Report problems with the Android Basics Unit 6 codelabs
title: 'Android Basics Unit 6 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet#5

**In which task and step of the codelab can this issue be found?**
step 6

**Describe the problem**
You say that you must assign the listResult value to _status .value as follow:
 val listResult = MarsApi.retrofitService.getProperties()
 _status.value = listResult

But I thing that there is maybe an error because is MarsApi.retrofitService.**getPhotos()** instead of **.getProperties()**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@alejopp 
Thank you for reaching out to us. The typo is fixed and published:

![Screen Shot 2022-07-19 at 11 22 26 AM](https://user-images.githubusercontent.com/86437155/179821914-ebf6ad7c-526e-48f4-a7b3-3d56afc15fbf.png)
