### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by jhuerta2999** [google-developer-training/android-basics-kotlin-mars-photos-app#140]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-internet-images#3

**In which task and step of the codelab can this issue be found?**
step 9 of Add Recycler View

**Describe the problem**
In the step, it is mentioned to open up the gridview_item.xml, but the correct file name is frid_view_item.xml. There is a typo in which file we are told to open.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/51420759/174335414-f7825d73-eba9-452a-b709-40f0940a1b9b.png)
![image](https://user-images.githubusercontent.com/51420759/174335441-bee980ab-35fd-4e1e-a03d-7ca115b1acbc.png)

**Comment by osuleymanova** [comment]
Hello @jhuerta2999,

Thank you for reaching out to us. The typo is fixed and will be published soon.
