### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by alessandrodalbello** [google-developer-training/android-basics-kotlin-mars-photos-app#15]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images#2

**In which task and step of the codelab can this issue be found?**
Task: Display an internet image
Step: Update the ViewModel

**Describe the problem**
The example image is incorrect. It is not a screenshot of the URL of the first image from Mars, but instead an example of a connectivity issue message.

**Comment by charles-allen** [comment]
Here's the image in question:

| Current screenshot (network error)  | My screenshot (network success) |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/31621095/114312216-25c52a00-9b1c-11eb-93f9-d30e7ea27a5d.png" width="500" /> | <img src="https://user-images.githubusercontent.com/31621095/114312229-2d84ce80-9b1c-11eb-8aac-f7e8fe474013.png" width="500" /> |

**Comment by osuleymanova** [comment]
@alessandrodalbello 
Thank you for reaching out to us. The image was updated and published.
![Screen Shot 2022-04-12 at 2 45 40 PM](https://user-images.githubusercontent.com/86437155/163059822-6513e6ce-1d2e-4313-a03d-fd6dd391ae49.png)
