### ISSUE TITLE
Android Basics: Load and display images from the Internet - Incorrect name of image library

### ISSUE THREAD

**Issue by charles-allen** [google-developer-training/android-basics-kotlin-mars-photos-app#17]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images#2

**In which task and step of the codelab can this issue be found?**
"3. Display an internet image"

**Describe the problem**
In "Add loading and error images", step 5, it says:

> Run the app. Depending on the speed of your network connection, you might briefly see the loading image as **Glide** downloads and displays the property image.

...but the training uses **Coil**, not Glide.

_Edit: Section 8 "Learn More" also focuses on Glide, not Coil_

**Comment by osuleymanova** [comment]
@charles-allen 
Thank you for reaching out to us. The typo was fixed and published:
![Screen Shot 2022-04-12 at 2 53 35 PM](https://user-images.githubusercontent.com/86437155/163060780-16d3d30b-30b1-4b87-a690-e30fa2703513.png)
![Screen Shot 2022-04-12 at 2 51 32 PM](https://user-images.githubusercontent.com/86437155/163060802-fed240fe-cd4f-49de-9092-56f935777481.png)
