### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by ErnestasOkunevic** [google-developer-training/android-basics-kotlin-mars-photos-app#19]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5

**In which task and step of the codelab can this issue be found?**
Get data from the internet --> task #6 Connecting to the Internet

**Describe the problem**

Where: Call the web service in OverviewViewModel --> step #5
What's wrong: incorrect name of function is used
It states that the .getProperties() function needs to be used, while what we actually need to use is .getPhotos()

**Steps to reproduce?**
1. Go to the provided URL
2. Scroll down to the bottom
3. You can now see step #5 and the incorrect function name

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/69603541/115126682-9a470f80-9fd9-11eb-8a0b-760b31c1c885.png)

**Comment by gitgrimbo** [comment]
Duplicates
#58
#55
#50
#38
#31
#29
#21
#19
#14
#13

**Comment by osuleymanova** [comment]
@ErnestasOkunevic 
Thank you for reaching out to us. The issue is fixed and published:

https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5
