### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by kirvedx** [google-developer-training/android-basics-kotlin-mars-photos-app#20]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-internet-images#3

**In which task and step of the codelab can this issue be found?**

*Task 4* -> *List Adapter (Refresher)* -> *Step 4*

**Describe the problem**

The import is incorrect:

> `Import androidx.recyclerview.widget.RecyclerView` and 
> `com.example.android.marsrealestate.databinding.GridViewItemBinding if requested.`

It should be: `com.example.android.marsphotos.databinding.GridViewItemBinding`

**Proof**:
![Proof Of Mistake](https://drive.google.com/file/d/187w-izfP2T4usrRgmmTEMzUEuqDo5dFe/view?usp=sharing)

**Steps to reproduce?**
1. Go to... *The above URL*
2. Click on... *Task 4*
3. See error... *In List Adapter section, specifically Step 4*

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![screenshot-developer android com-2021 04 17-22_11_00](https://user-images.githubusercontent.com/6693085/115132037-b3948f80-9fca-11eb-91c2-69d44abf6293.png)

**Comment by osuleymanova** [comment]
@kirvedx 
Thank you for reaching out to us. The issue is fixed and published.
