### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by hassan0599** [google-developer-training/android-basics-kotlin-mars-photos-app#22]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5

**In which task and step of the codelab can this issue be found?**
Task: 6
Step: "Object declarations"
Sub-step: 3

**Describe the problem**
The text "the caller will access the same a singleton Retrofit object" should read "the caller will access the same singleton Retrofit object".

_Include screenshots if they would be useful in clarifying the problem._
![Screenshot 2021-04-25 131728](https://user-images.githubusercontent.com/61388284/116002712-ff49c900-a5c8-11eb-8265-9da70959da5c.jpg)

**Comment by osuleymanova** [comment]
@hassan0599 
Thank you for reaching out to us. The issue is fixed and published.
