### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by hassan0599** [google-developer-training/android-basics-kotlin-mars-photos-app#23]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-internet-images#2

**In which task and step of the codelab can this issue be found?**
Task: 3
Step: "Update the ViewModel"
Sub-step: 7

**Describe the problem**
The image that is shown doesn't accurately represent what should happen if it the instructions are followed. The incorrect image and the correct image are attached below.

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot 2021-04-25 144802](https://user-images.githubusercontent.com/61388284/116005792-82255080-a5d6-11eb-8ebb-93717dd05ecb.jpg)
![Screenshot 2021-04-25 145325](https://user-images.githubusercontent.com/61388284/116005795-83ef1400-a5d6-11eb-8dd1-aa8449d1d519.jpg)

**Comment by osuleymanova** [comment]
@hassan0599 
Thank you for reaching out to us. The image was updated and published:
![Screen Shot 2022-04-12 at 2 45 40 PM](https://user-images.githubusercontent.com/86437155/163060994-f9c51bfd-6b34-4ad6-a735-5b6b782d2c95.png)
