### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by hassan0599** [google-developer-training/android-basics-kotlin-mars-photos-app#24]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-internet-images#2

**In which task and step of the codelab can this issue be found?**
Task: 3
Step: "Use Binding Adapters"
Sub-step: 4

**Describe the problem**
The text "add a let{} block to the imageURL argument" should read "add a let{} block to the imgUrl argument"

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot 2021-04-25 175314](https://user-images.githubusercontent.com/61388284/116010841-87db6000-a5ef-11eb-8ee8-af21858362d7.jpg)

**Comment by osuleymanova** [comment]
@hassan0599 
Thank you for reaching out to us. The typo was fixed and published:

![Screen Shot 2022-04-12 at 3 27 21 PM](https://user-images.githubusercontent.com/86437155/163065119-f53fa090-bbb0-47b6-a51f-1523d139eea5.png)
