### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by FilipPalusinski** [google-developer-training/android-basics-kotlin-mars-photos-app#25]
---
name: Android Basics Unit 4 issue
about: Typo and missing suspend keyword in code.
title: 'Android Basics Unit 4 issue:'

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#7

**In which task and step of the codelab can this issue be found?**
8. Parse the JSON response with Moshi
Update MarsApiService and OverviewViewModel
step 5. Now that you have the MoshiConverterFactory in place...

**Describe the problem**
In provided code:
interface MarsApiService {
   @GET("photo")
   fun getPhotos(): List<MarsPhoto>
}

There is a typo in word "photo", the endpoint name is "photos" and the function hasn't got a "suspend" keyword. 

In Solution Code task you provide this code:
interface MarsApiService {
   /**
    * Returns a [List] of [MarsPhoto] and this method can be called from a Coroutine.
    * The @GET annotation indicates that the "photos" endpoint will be requested with the GET
    * HTTP method
    */
   @GET("photos")
   suspend fun getPhotos() : List<MarsPhoto>
}

In this code the endpoint name is "photos" and function has suspend keyword so its correct.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...
4. That's it :)

**Comment by osuleymanova** [comment]
@FilipPalusinski 
Thank you for reaching out to us. The issue is fixed and published.
