### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by ndorigatti** [google-developer-training/android-basics-kotlin-mars-photos-app#26]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-internet-images#2

**In which task and step of the codelab can this issue be found?**
Load and display images from the Internet
Step 3 - Display an internet image -> Update the ViewModel

**Describe the problem**
At the last element (7), the codelab says to run the app, and that is shows the url:
"Run the app. The TextView now displays the URL of the first Mars photo. All you've done so far is set up the ViewModel and the LiveData for that URL."
But the picture below is one with Airplane Mode and with an error shown.
![image](https://user-images.githubusercontent.com/3414365/116372473-b7b37f00-a80c-11eb-877b-fc637c9ae217.png)

**Steps to reproduce?**
1. Go to the page
2. Scroll Before "Use Binding Adapters" section
3. See error in the picture.

**Versions**
Any version, issue is in the web page

**Additional information**

**Comment by osuleymanova** [comment]
@ndorigatti 
Thank you for reaching out to us. The image was updated and published:
![Screen Shot 2022-04-12 at 2 45 40 PM](https://user-images.githubusercontent.com/86437155/163065285-bc0d4d3a-55c3-4e7b-850d-9cfcea7ed429.png)
