### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by nadym89** [google-developer-training/android-basics-kotlin-mars-photos-app#27]
Image below 7th point of Update the **ViewModel** heading

The Image (https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images/img/b8ac93805b69b03a.png) seems to be a wrong image since it is displaying an error.

**Comment by osuleymanova** [comment]
@nadym89 
Thank you for reaching out to us. The image was updated and published:
![Screen Shot 2022-04-12 at 2 45 40 PM](https://user-images.githubusercontent.com/86437155/163065991-0a2d20bc-3c8d-4d3c-88a7-7255d257c4c2.png)
