### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by jap1968** [google-developer-training/android-basics-kotlin-mars-photos-app#28]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet

**In which task and step of the codelab can this issue be found?**
Task: Get data from the internet
Step: 8. Parse the JSON response with Moshi

**Describe the problem**
In the section "Update MarsApiService and OverviewViewModel", step 5:
"Now that you have the MoshiConverterFactory in place,..."

Instead of:
interface MarsApiService {
   @GET("photo")
   fun getPhotos(): List<MarsPhoto>
}

The code should be:
interface MarsApiService {
   @GET("photo")
   suspend fun getPhotos(): List<MarsPhoto>
}

**Steps to reproduce?**
You will get an error if you try to run the sample code without the "suspend" word

**Versions**
_Android Studio version:_ 4.1.3
_API version of the emulator:_ API 28

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@jap1968 
Thank you for reaching out to us. The issue is fixed and published.
