### ISSUE TITLE
Android Basics: Loading and displaying images from the Internet

### ISSUE THREAD

**Issue by AlexandrePlus** [google-developer-training/android-basics-kotlin-mars-photos-app#3]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images#3

**In which task and step of the codelab can this issue be found?**
4. Display a grid of images with a RecyclerView > Add Recyclerview > 1. Open layout/gridview_item...

**Describe the problem**
It is written gridview_item.xml instead of grid_view_item.xml (see https://github.com/google-developer-training/android-basics-kotlin-mars-photos-app/blob/starter/app/src/main/res/layout/grid_view_item.xml )

**Comment by AlexandrePlus** [comment]
idem for "8. According to the Material design guidelines, [...] in gridview_item.xml layout." instead of grid_view_item.xml

**Comment by AlexandrePlus** [comment]
idem for "8. According to the Material design guidelines, [...] in gridview_item.xml layout." instead of grid_view_item.xml

**Comment by AlexandrePlus** [comment]
idem for "9. Open layout/gridview_item.xml." instead of grid_view_item.xml

**Comment by jhansitavva** [comment]
@AlexandrePlus 
Thank you so much for reporting this issue. This is fixed and will be published soon.
