### ISSUE TITLE
Android Basics: Loading and displaying images from the Internet

### ISSUE THREAD

**Issue by Tuitsuchi** [google-developer-training/android-basics-kotlin-mars-photos-app#30]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%3Fhl%3Dja%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-internet-images#3

**In which task and step of the codelab can this issue be found?**
4. Display a grid of images with a RecyclerView of Add Recyclerview step's context may have typo.

**Describe the problem**
Add Recyclerview step's context may have typo.

> In this step you will change the app's layout to use a recycler view with a grid layout, rather than the single image view.
> 
> Open layout/gridview_item.xml. Remove the viewModel data variable.
> Inside the <data> tag, add the following photo variable of the type MarsPhoto.
> 
So,
layout/gridview_item.xml -> layout/grid_view_item.xml

**Comment by osuleymanova** [comment]
@Tuitsuchi 
Thank you for reaching out to us. The issue was fixed and published: 
![Screen Shot 2022-04-12 at 3 39 57 PM](https://user-images.githubusercontent.com/86437155/163066316-c6f85140-764d-4595-8827-5c6e7a4d684a.png)
