### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by hndang** [google-developer-training/android-basics-kotlin-mars-photos-app#31]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?authuser=2&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%3Fauthuser%3D2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5

**In which task and step of the codelab can this issue be found?**
Step 6 - 5

**Describe the problem**
I think this code might be from another codelab:

 val listResult = MarsApi.retrofitService.getProperties()
 _status.value = listResult

getProperties() is not implemented in the interface. 

**Steps to reproduce?**
1. Go to...NA
2. Click on...NA
3. See error...NA

**Versions**
_Android Studio version:_ NA
_API version of the emulator:_ NA

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._NA

**Comment by gitgrimbo** [comment]
Duplicates
#58
#55
#50
#38
#31
#29
#21
#19
#14
#13

**Comment by osuleymanova** [comment]
@hndang 
Thank you for reporting this issue. It is fixed and published:

https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5
