### ISSUE TITLE
Android Basics: Get data from the Internet - Missing moshi-kotlin library import

### ISSUE THREAD

**Issue by hndang** [google-developer-training/android-basics-kotlin-mars-photos-app#33]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?authuser=2&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%3Fauthuser%3D2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#7

**In which task and step of the codelab can this issue be found?**
step 8

**Describe the problem**
This missing implementation of moshi library

`implementation 'com.squareup.moshi:moshi-kotlin:1.12.0'`

Without it you wont' have `KotlinJsonAdapterFactory`

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@hndang 
Thank you for reaching out to us. The issue is fixed and published.
