### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by Rayishere** [google-developer-training/android-basics-kotlin-mars-photos-app#34]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-internet-images#3

**In which task and step of the codelab can this issue be found?**
The description regarding to create a bind() method that takes a MarsPhoto object as an argument and sets binding.property to that object. Need to be more explicit with related configuration on _grid_view_item.xml_.
🔻 _PhotoGridAdapter.kt_
```
fun bind(MarsPhoto: MarsPhoto) {
   binding.photo = MarsPhoto //  the error is here
   binding.executePendingBindings()
}
```
**Describe the problem**
I kept run into the error which could not go away event though I clean and rebuild the project multiple times. This is quite frustrating in the first place. 😥

🔻the error
> D:\11-Andoid_IDE\Project\android-basics-kotlin-mars-photos-app\app\build\generated\source\kapt\debug\com\example\android\marsphotos\DataBinderMapperImpl.java:10: error: cannot find symbol
import com.example.android.marsphotos.databinding.GridViewItemBindingImpl;
                                                 ^
  symbol:   class GridViewItemBindingImpl
  location: package com.example.android.marsphotos.databinding

**Steps to reproduce?**
1. Go to... com/example/android/marsphotos/overview/PhotoGridAdapter.kt
2. Click on... Build > Clean Project and Build > Rebuild Project
3. See error... > D:\11-Andoid_IDE\Project\android-basics-kotlin-mars-photos-app\app\build\generated\source\kapt\debug\com\example\android\marsphotos\DataBinderMapperImpl.java:10: error: cannot find symbol

**Versions**
_Android Studio version:_ 30.0.2, 30.0.3
_API version of the emulator:_ 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/25098436/118916333-51c89c00-b961-11eb-9f85-6ac60b996035.png)

**How I resolve the error**
1. Go to... layout/grid_view_item.xml
2. Modify the `<data>` label and set the name variable into "photo"
```
  <data>
        <variable
            name="photo"
            type="com.example.android.marsphotos.network.MarsPhoto" />
    </data>
```
3. Click on... Build > Clean Project and Build > Rebuild Project
4. The project is error free and able to run 🎉

**Comment by citrusella** [comment]
I'm having this error at the step where you use the grid view to load one image.

Except that it's in a generated build file (and ONLY there), I've retraced my steps to see if I screwed something up (I didn't), and this fix won't work in that instance because the error seems to be in a different file I don't even have control over (there are no corresponding errors in things I've actually coded, AFAICT). Help? I've tried everything.

EDIT: Well. After several hours of deliberation, it seems it was a capitalization mismatch between the binding adapter and the bit you add to the ImageView. Which I feel like I should have suspected earlier, but literally nothing about the error or the files suggested that was the problem. 🤔 The moral is "always proofread extra carefully", I guess.

**Comment by Rayishere** [comment]
I can relate to the problem that you countered, since the capitalization mismatch is ticker to find. The red warning error message sometimes helpful for most of the time but others doesn't.  As for the moral that you mention about is quite right on the spot. 😆

**Comment by osuleymanova** [comment]
@Rayishere 
Thank you for reaching out to us and providing the screenshot. It looks like the wrong package name was imported. Please check the screenshots below:
![Screen Shot 2022-05-10 at 3 17 46 PM](https://user-images.githubusercontent.com/86437155/167731847-d07a820a-66f6-45fb-bb8c-b6f78d23cad0.png)
It should be:
![Screen Shot 2022-05-10 at 3 16 31 PM](https://user-images.githubusercontent.com/86437155/167731899-bcd6b3e0-1cc1-458a-9c96-f22e1cc5e00b.png)
If it doesn't help please feel free to re-open the ticket.
Happy coding!
