### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by tolgahantutar** [google-developer-training/android-basics-kotlin-mars-photos-app#36]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'

---

**https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-internet-images#2**

**Task Display an internet image Step 7**

**Image below step 7 shows that there is a failure when trying to access to the internet. But actually when user did all the process until step 7, it should show the first image's link instead of error. The image is wrong.**

**Comment by osuleymanova** [comment]
@tolgahantutar 
The issue that you presented to us is important, and I thank you for bringing it to our attention. The image was updated:
![Screen Shot 2022-04-12 at 2 45 40 PM](https://user-images.githubusercontent.com/86437155/163066622-836b07c8-83f7-471e-8163-cd8b09078cd3.png)
