### ISSUE TITLE
Android Basics: Loading and displaying images from the Internet

### ISSUE THREAD

**Issue by garrettgrimsley** [google-developer-training/android-basics-kotlin-mars-photos-app#4]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: 'documentation'

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images#2

**In which task and step of the codelab can this issue be found?**
Add loading and error images

**Describe the problem**
The sentence "Depending on the speed of your network connection, you might briefly see the loading image as **Glide** downloads and displays the property image. "

Should read **Coil**

**Comment by jhansitavva** [comment]
@garrettgrimsley 
Thank you so much for reporting this issue. This is fixed and will be published soon.
