### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by PatrissolJuns** [google-developer-training/android-basics-kotlin-mars-photos-app#48]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Load and display images from the Internet'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-internet-images#3

**In which task and step of the codelab can this issue be found?**
Step 4

**Describe the problem**
There's a typo error in first item of under the block **Add Recyclerview**. It's written **_layout/gridview_item.xml_** instead of **_layout/grid_view_item.xml_**

Also in step 3, under the block Add loading and error images, there's a **trailing d** at the end of the second item of the list. Bellow is the full sentence: 

> Open res/drawable/loading_animation.xml. This drawable is an animation that rotates an image drawable, loading_img.xml, around the center point. (You don't see the animation in the preview.) d

I hope it'd help

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@PatrissolJuns 
Thank you for reaching out to us. Your report helped a lot!The typo was fixed and published:
![Screen Shot 2022-04-12 at 3 39 57 PM](https://user-images.githubusercontent.com/86437155/163074325-66d32bf0-6495-4700-9dd4-8aed2f8b3aff.png)
"d" was removed as well:

![Screen Shot 2022-04-12 at 5 14 55 PM](https://user-images.githubusercontent.com/86437155/163074752-68dd422e-974d-4453-a8bf-6fef36261cee.png)
