### ISSUE TITLE
Android Basics: Get data from the Internet: inconsistent use of capital I in word 'internet'

### ISSUE THREAD

**Issue by bivanbi** [google-developer-training/android-basics-kotlin-mars-photos-app#49]
**URL of codelab**
[Get data from the internet](https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5)

**In which task and step of the codelab can this issue be found?**
Task 6: Connectiong to the Internet 

**Describe the problem**
Unit title and task title uses 'internet' capitalization inconsistently.

**Additional information**
![image](https://user-images.githubusercontent.com/8977026/120886240-37dbba00-c5ed-11eb-8f06-11f5a7639440.png)

**Comment by osuleymanova** [comment]
@bivanbi 
Thank you for reaching out to us. The issue is closed due to intentional behavior.
