### ISSUE TITLE
BindingAdapter instructions clarification

### ISSUE THREAD

**Issue by garrettgrimsley** [google-developer-training/android-basics-kotlin-mars-photos-app#5]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images#2

**In which task and step of the codelab can this issue be found?**
Display an internet image -> 
Create a binding adapter and use Coil -> 
2. In BindingAdapters.kt. Create a `bindImage()` function...

**Describe the problem**
The instructions here don't specify that the function should be defined *outside* of the class.
If you define the function *inside* the class then you'll receive an error like the following:

```
is not static and requires an object to use, retrieved from the DataBindingComponent. If you don't use an inflation method taking a DataBindingComponent, use DataBindingUtil.setDefaultComponent or make all BindingAdapter methods static.
```

**Steps to reproduce?**
1. Follow the instructions, but define your `BindingAdapter` function inside the `BindingAdapters` class
2. Run the app
3. See the binding error

**Comment by jhansitavva** [comment]
@garrettgrimsley 
Thank you for reporting this issue. This is fixed and will be published soon.
