### ISSUE TITLE
Android Basics: Get data from the Internet: Unresolved reference: getProperties

### ISSUE THREAD

**Issue by bivanbi** [google-developer-training/android-basics-kotlin-mars-photos-app#50]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
[Get data from the internet](https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5)

**In which task and step of the codelab can this issue be found?**
Task 6 step 5 

**Describe the problem**
Task says:
*"5. Assign the result we just received from the backend server to the ```_status.value```."*
```
 val listResult = MarsApi.retrofitService.getProperties()
 _status.value = listResult
```

Problem is: ```Unresolved reference: getProperties()```

Checked with the solution code, and it indeed seems like ```getProperties()``` method would not be used anyway.

Solution code:
```
    private fun getMarsPhotos() {

        viewModelScope.launch {
            _status.value = MarsApiStatus.LOADING
            try {
                _photos.value = MarsApi.retrofitService.getPhotos()
                _status.value = MarsApiStatus.DONE
            } catch (e: Exception) {
                _status.value = MarsApiStatus.ERROR
                _photos.value = listOf()
            }
        }
    }
```

**Comment by gitgrimbo** [comment]
Duplicates
#58
#55
#50
#38
#31
#29
#21
#19
#14
#13

**Comment by osuleymanova** [comment]
@bivanbi 
Thank you for reaching out to us and for the solution code provided. The issue is fixed and published:

https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5
