### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by Joktaa** [google-developer-training/android-basics-kotlin-mars-photos-app#52]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue: example of result'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-internet-images#2

**In which task and step of the codelab can this issue be found?**
'Update the ViewModel' > step 7

**Describe the problem**
The image of the example show an error.

**Additional information**
![image](https://user-images.githubusercontent.com/37557707/121491555-591a1d00-c9d6-11eb-82fd-9275f21eeaa5.png)

**Comment by osuleymanova** [comment]
@Joktaa 
Thank you for reaching out to us. The image was updated:
![Screen Shot 2022-04-12 at 2 45 11 PM](https://user-images.githubusercontent.com/86437155/163074836-56405f4e-205b-4a7b-ace7-e80d7f51e5db.png)
