### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by usndangol97** [google-developer-training/android-basics-kotlin-mars-photos-app#53]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5

**In which task and step of the codelab can this issue be found?**
in object declaration of MarsApi

**Describe the problem**
It shows the error:

Property delegate must have a 'getValue(MarsApiService.MarsApi, KProperty<*>)' method. None of the following functions is suitable: 
public inline operator fun <T> Lazy<MarsApiService.MarsApiService>.getValue(thisRef: Any?, property: KProperty<*>): MarsApiService.MarsApiService defined in kotlin

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by TheReformedAlloy** [comment]
Hey there, I know it's about a month late, but I realized that when I was doing this I ran into the same issue because I thought this all was supposed to be contained in a class definition. However, all of the code is supposed to be in file scope.
