### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by carlosjimz87** [google-developer-training/android-basics-kotlin-mars-photos-app#56]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-internet-images#2

**In which task and step of the codelab can this issue be found?**
Unit 4: Connect to the internet
Pathway 2: Get and display data from the internet
Section 3: Load and display images from the internet
Task 3: Display an internet image
Step 7. Run the app. The TextView now displays the URL of the first Mars photo. All you've done so far is set up the ViewModel and the LiveData for that URL.

**Describe the problem**
The image in this step shows an error instead of the URL of the first Mars photo.

**Additional information**

![image](https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images/img/b8ac93805b69b03a.png)

**Comment by osuleymanova** [comment]
@carlosjimz87 
Thank you for reaching out to us. It's already handled:
![Screen Shot 2022-04-12 at 2 45 40 PM](https://user-images.githubusercontent.com/86437155/163071841-4cb17626-560c-48cd-98bb-ba4a04950e2b.png)
