### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by MxWild** [google-developer-training/android-basics-kotlin-mars-photos-app#59]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-internet-images#2

**In which task and step of the codelab can this issue be found?**
Create a binding adapter and use Coil

**Describe the problem**
If you create fun bindImage(imgView: ImageView, imgUrl: String?)  without  @JvmStatic annotation and than after compile and run app on android emulator you will get an error type: "is not static and requires an object to use, retrieved from the DataBindingComponent". And I found BindingAdapters needs be object except class.

**Versions**
_Android Studio version:_ 4.2.1
_API version of the emulator:_ Name: Pixel_3a_API_29
CPU/ABI: Google Play Intel Atom (x86)
 (API level 29)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/28675044/123114911-57c20900-d448-11eb-9d71-d527dc584f44.png)

**Comment by aglover-zendesk** [comment]
I ran into the same issue. Not sure if it's operator error on my part. Based on @MxWild suggestion, I was able to get the example working with this code for `BindingAdapters.kt`:

```kotlin
package com.example.android.marsphotos

import android.widget.ImageView
import androidx.core.net.toUri
import androidx.databinding.BindingAdapter
import coil.load

object BindingAdapters {
    @BindingAdapter("imageUrl")
    @JvmStatic
    fun bindImage(imgView: ImageView, imgUrl: String?) {
        imgUrl?.let {
            val imgUri = imgUrl.toUri().buildUpon().scheme("https").build()
            imgView.load(imgUri)
        }
    }
}
```

**Comment by kristoftorfs** [comment]
Actually, BindingAdapters.kt is not a class or object, it should simply contain the function:

```kotlin
package com.example.android.marsphotos

import android.widget.ImageView
import androidx.core.net.toUri
import androidx.databinding.BindingAdapter
import coil.load

@BindingAdapter("imageUrl")
fun bindImage(imgView: ImageView, imgUrl: String?) {
    imgUrl?.let {
        val imgUri = imgUrl.toUri().buildUpon().scheme("https").build()
        imgView.load(imgUri)
    }
}
```
