### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by gaurav-rajput123** [google-developer-training/android-basics-kotlin-mars-photos-app#6]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-internet-images#2

**In which task and step of the codelab can this issue be found?**
Step #3 

**Describe the problem**
Wrong image is shown here

**Steps to reproduce?**
1. Go to... step 7 of update the viewModel
2. there is the wrong image show there instead of the imae with the url on the screen it is showing network error screen

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jhansitavva** [comment]
@gaurav-rajput123 
Thank you so much for reporting this issue. 
Replaced screenshot.
This is fixed and will be published soon.
