### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by aravindvaddi** [google-developer-training/android-basics-kotlin-mars-photos-app#60]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#7

**In which task and step of the codelab can this issue be found?**
"Get data from the internet"
Step 8

**Describe the problem**
Problem: Typo in the below code.
The getPhotos() function needs to have a suspend keyword and the API endpoint is 'photos', 'photo' is returning a 404 error.
```
interface MarsApiService {
   @GET("photo")
   fun getPhotos(): List<MarsPhoto>
}
```
It should be the below instead (I tested it)
```
interface MarsApiService {
   @GET("photos")
   suspend fun getPhotos(): List<MarsPhoto>
}
```

**Steps to reproduce?**
1. Go to the page
2. Scroll down a little bit (I'm not sure how to specify how much)
3. Error can be found in the code snippet
```
interface MarsApiService {
   @GET("photo")
   fun getPhotos(): List<MarsPhoto>
}
```

**Versions**
_Android Studio version: 4.2.1
_API version of the emulator: 30 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@aravindvaddi 
Thank you for reaching out to us. The issue is fixed and published.
