### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by jake0sand** [google-developer-training/android-basics-kotlin-mars-photos-app#61]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#7

Parse the JSON response with Moshi
When you are tasked with changing the getPhotos() type from string to List<MarsPhoto>,
GET("photos") is shown as GET("photo")

It should read:
interface MarsApiService {
   @GET("photos")  <--------------------------- This is the correction ------------------ GET("photo") to GET("photos")
   fun getPhotos(): List<MarsPhoto>
}

**Comment by osuleymanova** [comment]
@jake0sand 
Thanks for reporting this issue. It will be fixed and published soon.
