### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by Abhimanyu14** [google-developer-training/android-basics-kotlin-mars-photos-app#62]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#7

**In which task and step of the codelab can this issue be found?**
Get data from the internet - Step 8

**Describe the problem**

In the code,
```
interface MarsApiService {
   @GET("photo")
   fun getPhotos(): List<MarsPhoto>
}
```

`suspend` is missing.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Abhimanyu14 
Thank you for reaching out to us. The issue is fixed and published.
