### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by muahahahh** [google-developer-training/android-basics-kotlin-mars-photos-app#64]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5

**In which task and step of the codelab can this issue be found?**
Step 6, almost in the end

**Describe the problem**
The method should be 
 val listResult = MarsApi.retrofitService.**getPhotos()**
 _status.value = listResult
instead of 
**.getProperties()**

![Screenshot 2021-07-06 214507](https://user-images.githubusercontent.com/32815793/124657967-75a95800-dea3-11eb-9736-d416501e148e.png)

**Comment by osuleymanova** [comment]
@muahahahh 
Thank you for reaching out to us. The issue is fixed and will be published soon.
