### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by sahalsm** [google-developer-training/android-basics-kotlin-mars-photos-app#68]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#7

**In which task and step of the codelab can this issue be found?**
8th Task and 5th Step

**Describe the problem**
interface MarsApiService {
   @GET("photo")
   fun getPhotos(): List<MarsPhoto>
}

this throws an error 
it will be fixed by adding suspend before fun 
 
interface MarsApiService {
   @GET("photo")
   suspend fun getPhotos(): List<MarsPhoto>
}

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@sahalsm 
Thank you for reaching out to us. The issue is fixed and published.
