### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by Stavrenas** [google-developer-training/android-basics-kotlin-mars-photos-app#69]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#7

**In which task and step of the codelab can this issue be found?**
On section 8 step 5

**Describe the problem**
The code is;
![Screenshot from 2021-07-20 18-03-23](https://user-images.githubusercontent.com/7922854/126348188-e846dee1-26da-460b-9647-28df9db3b928.png)

interface MarsApiService {
   @GET("photo")
   fun getPhotos(): List<MarsPhoto>
}

but it should be 

interface MarsApiService {
   @GET("photos")
   fun getPhotos(): List<MarsPhoto>
}

Note the missing "s" in "photo" 
This causes an exception and the application does not run as intended

**Comment by osuleymanova** [comment]
@Stavrenas 
Thank you for reaching out to us. The issue is fixed and published.
