### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by catosh** [google-developer-training/android-basics-kotlin-mars-photos-app#7]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:' missin suspend qualifier to getPhotos
labels: ''
assignees: ''

---

**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#7

**In which task and step of the codelab can this issue be found?**
at point 7, you wrote:

interface MarsApiService {
   @GET("photo")
   fun getPhotos(): List<MarsPhoto>
}

**Describe the problem**
The app fails with error "Failure: unable to create call adapter for java.util.List<com.example.android.marsphotos.network.MarsPhoto> from methdo MarsApiService.getPhotos

**Additional information**
just add "suspend" keyword again and everything works fine. 
interface MarsApiService {
   @GET("photo")
 suspend fun getPhotos(): List<MarsPhoto>
}

**Comment by osuleymanova** [comment]
@catosh 
Thank you for reaching out to us. The issue is fixed and published.
