### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by Stavrenas** [google-developer-training/android-basics-kotlin-mars-photos-app#70]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-internet-images#2

**In which task and step of the codelab can this issue be found?**
task 3 step 7

**Describe the problem**
Wrong screenshot. The screenshot should display the image URL , not  an error message

**Comment by osuleymanova** [comment]
@Stavrenas 
Thank you for reaching out to us. The image is updated and published:
![Screen Shot 2022-04-12 at 2 45 40 PM](https://user-images.githubusercontent.com/86437155/163071434-8f84beb0-ecf9-47f4-b100-2f20cda3c791.png)
