### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by Stavrenas** [google-developer-training/android-basics-kotlin-mars-photos-app#71]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-internet-images#4

**In which task and step of the codelab can this issue be found?**
task 5 step 3

**Describe the problem**
Missing left bracket after catch

The code is;
try {
    _photos.value = MarsApi.retrofitService.getPhotos()
    _status.value = MarsApiStatus.DONE
} catch (e: Exception) 
     _status.value = MarsApiStatus.ERROR
}

and should be 
try {
    _photos.value = MarsApi.retrofitService.getPhotos()
    _status.value = MarsApiStatus.DONE
} catch (e: Exception) {
     _status.value = MarsApiStatus.ERROR
}

**Comment by osuleymanova** [comment]
@Stavrenas 
Thank you for reaching out to us. The code snippet is updated:
![Screen Shot 2022-04-12 at 4 38 37 PM](https://user-images.githubusercontent.com/86437155/163071673-1ab1bc41-c099-4468-99a7-c24011c70bd9.png)
