### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by wlagunzad** [google-developer-training/android-basics-kotlin-mars-photos-app#72]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#7

**In which task and step of the codelab can this issue be found?**
Step 8

**Describe the problem**

interface MarsApiService {
   @GET("photo")
   fun getPhotos(): List<MarsPhoto>
}

should say @GET("photos") <-- needs the "s"

**Steps to reproduce?**

**Versions**

**Additional information**

**Comment by osuleymanova** [comment]
@wlagunzad 
Thank you for reaching out to us. The issue is fixed and published.
