### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by divercraig** [google-developer-training/android-basics-kotlin-mars-photos-app#74]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images

**In which task and step of the codelab can this issue be found?**
Task 3 - Step 7

**Describe the problem**
In step 7 the screenshot shown should show a status message like "First Mars image URL: HTTP://mars.jps..." but the screenshot shown in the code lab shows a status message like "Failure: Unable to resolve host..."

**Steps to reproduce?**
1. Go to... the code lab and complete all the steps up to task 3, step 7 (including the previous code lab)
2. Click on... start the application as requested in step 7
3. See error... the application works and displays the intended URL of the mars image, but the screenshot in the codelab shows a failure

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
Code Lab Image:
![image](https://user-images.githubusercontent.com/3470279/129438834-2d3af04d-012c-4199-9da1-d8513b3219c6.png)
Actual Output:
![image](https://user-images.githubusercontent.com/3470279/129438851-7aafff91-4a84-442b-8351-f5a30d500a3e.png)

**Comment by osuleymanova** [comment]
@divercraig 
Thank you for reaching out to us. It's already handled:
![Screen Shot 2022-04-12 at 2 45 40 PM](https://user-images.githubusercontent.com/86437155/163066860-f052d270-7171-4b64-af1c-3e27670a63cb.png)
