### ISSUE TITLE
Android Basics: Coroutines

### ISSUE THREAD

**Issue by iranfard** [google-developer-training/android-basics-kotlin-mars-photos-app#76]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-introduction-coroutines?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-introduction-coroutines#3

**In which task and step of the codelab can this issue be found?**
4. Coroutines in Kotlin

**Describe the problem**
The descriptions are so vague and brief, I have to search for other resources to learn about coroutines

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@iranfard 
Thank you for reaching out to us and providing your feedback. Our apologies for this inconvenience caused. The actions for codelab content improvement will be taken soon.
