### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by paviotti** [google-developer-training/android-basics-kotlin-mars-photos-app#77]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?hl=pt-br&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%3Fhl%3Dpt-br%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5

**In which task and step of the codelab can this issue be found?**

6
**Describe the problem**

it's not .getProperties()
it's a .getPhotos()

![erro do google 1](https://user-images.githubusercontent.com/48533439/131896163-55245f9f-96e6-4b54-bb7f-a638d679039b.jpg)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@paviotti 
Thank you for reaching out to us. The issue is fixed and published.
