### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by nmozaka** [google-developer-training/android-basics-kotlin-mars-photos-app#8]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

Here the .getProperties() should change to .getPhotos():

5. Assign the result we just received from the backend server to the _status.value.

 val listResult = MarsApi.retrofitService.getProperties()
 _status.value = listResult

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jhansitavva** [comment]
@nmozaka 
Thank you so much for reporting this issue. This is fixed and will be published soon.
