### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by Andrey-Metelyov** [google-developer-training/android-basics-kotlin-mars-photos-app#80]
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#:~:text=Retrofit%20return%20a%20list%20of%20MarsPhoto%20objects%2C%20instead%20of%20returning%20String.

Code snippet
```
interface MarsApiService {
   @GET("photo")
   fun getPhotos(): List<MarsPhoto>
}
```
should be
```
interface MarsApiService {
   @GET("photos")
   fun getPhotos(): List<MarsPhoto>
}
```

`@GET("photos"), not @GET("photo")`
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Duplicates:
#61 
#69 
#72 
#86 
#87

**Comment by osuleymanova** [comment]
@Andrey-Metelyov 
Thank you for reaching out to us. The issue is fixed and published.
