### ISSUE TITLE
Android Basics: Load and display images from the Internet

### ISSUE THREAD

**Issue by dremdilly** [google-developer-training/android-basics-kotlin-mars-photos-app#82]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-internet-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-internet-images#2

**In which task and step of the codelab can this issue be found?**
On step number 3 "Display an internet image" and task "Update the View Model" to number 7.

**Describe the problem**
There is the wrong screenshot after the lines 
"Run the app. The TextView now displays the URL of the first Mars photo. All you've done so far is set up the ViewModel and the LiveData for that URL."
On screenshot it shows a Failure, while there should be a text with "First Image URL" with correct URL of first Mars photo.

**Steps to reproduce?**
1. Go to step number 3 "Display an internet image" and task "Update the view model" till the number 7 step of this task.
2. View wrong screenshot on this step.
3. Find the wrong text on screenshot of the app that contradict the following text 
"Run the app. The TextView now displays the URL of the first Mars photo. All you've done so far is set up the ViewModel and the LiveData for that URL."

**Versions**
_Android Studio version:_ 4.1.3

_API version of the emulator:_ 29

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot 2021-09-16 164742](https://user-images.githubusercontent.com/73487673/133599268-f7aaa386-4e98-434e-8b4d-abede8b5099a.png)

**Comment by osuleymanova** [comment]
@dremdilly 
The issue that you presented to us is important, and I thank you for bringing it to our attention. The image was updated:
![Screen Shot 2022-04-12 at 2 45 40 PM](https://user-images.githubusercontent.com/86437155/163066754-1adb2ca2-d6a1-42e8-b596-7799b6c97292.png)
