### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by Ziad-Sameh1** [google-developer-training/android-basics-kotlin-mars-photos-app#84]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#4

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
The web server from which I can get mars photos is not working and here is the link: https://android-kotlin-fun-mars-server.appspot.com/

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Ziad-Sameh1 
Thank you for reaching out to us. 
Please try this link: https://android-kotlin-fun-mars-server.appspot.com/photos
