### ISSUE TITLE
Android Basics: Coroutines

### ISSUE THREAD

**Issue by xinneph** [google-developer-training/android-basics-kotlin-mars-photos-app#85]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-introduction-coroutines#3

**In which task and step of the codelab can this issue be found?**
in provided example:
```
fun CoroutineScope.launch {
    context: CoroutineContext = EmptyCoroutineContext,
    start: CoroutineStart = CoroutineStart.DEFAULT,
    block: suspend CoroutineScope.() -> Unit
}
```

**Describe the problem**
I guess it should be:
```
fun CoroutineScope.launch(
    context: CoroutineContext = EmptyCoroutineContext,
    start: CoroutineStart = CoroutineStart.DEFAULT,
    block: suspend CoroutineScope.() -> Unit
)
```

**Comment by osuleymanova** [comment]
@xinneph 
Thank you for reaching out to us. Your concern regarding the code provided in the codelab was correct. The actions were taken for updating it:
![Screen Shot 2022-04-15 at 11 46 00 AM](https://user-images.githubusercontent.com/86437155/163612867-3fd770ef-b3da-47d9-8f49-57606c254b6a.png)
Happy coding!
