### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by CodexMachinator** [google-developer-training/android-basics-kotlin-mars-photos-app#86]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#7

**In which task and step of the codelab can this issue be found?**
8. Parse the JSON response with Moshi

**Describe the problem**
code snippet reads:
```
interface MarsApiService {
   @GET("photo")
   fun getPhotos(): List<MarsPhoto>
}
```

should read:
```
interface MarsApiService {
   @GET("photos")
   suspend fun getPhotos(): List<MarsPhoto>
}
```

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Duplicates:
#87 
#72 
#69 
#61

**Comment by osuleymanova** [comment]
@CodexMachinator 
Thank you for reaching out to us. The issue is fixed and published.
