### ISSUE TITLE
Android Basics: Coroutines

### ISSUE THREAD

**Issue by FedericoTorsello** [google-developer-training/android-basics-kotlin-mars-photos-app#88]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-introduction-coroutines?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-introduction-coroutines#3

**In which task and step of the codelab can this issue be found?**
4. Coroutines in Kotlin

**Describe the problem**
"fun CoroutineScope.launch" don't have parentheses "()"

"Fun CoroutineScope.async()" start with capital 'F'

**Additional information**
![image](https://user-images.githubusercontent.com/6788571/137298693-d9715537-c836-4ae9-b140-893402f9cf34.png)
![image](https://user-images.githubusercontent.com/6788571/137298765-26fbe90c-8071-4de9-82dd-e4a16ae3af10.png)

**Comment by osuleymanova** [comment]
@FedericoTorsello 
The issues that you presented to us are very important, and I thank you for bringing them to our attention. The code snippets are updated:
![Screen Shot 2022-04-15 at 11 46 00 AM](https://user-images.githubusercontent.com/86437155/163609126-265606c9-49a4-40c2-b5ef-80ccf9334f84.png)
![Screen Shot 2022-04-15 at 11 46 28 AM](https://user-images.githubusercontent.com/86437155/163609146-1a672893-7ebe-487b-ac6b-de0b9adab326.png)
