### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by muhammad-farhan-bakht** [google-developer-training/android-basics-kotlin-mars-photos-app#89]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#7

**In which task and step of the codelab can this issue be found?**
On 8th page: Parse the JSON response with Moshi

**Describe the problem**
Missing suspend keyword in MarsApiService interface function `getPhotos()`.

**Additional information**
![missed suspend keyword](https://user-images.githubusercontent.com/26104308/137962179-9c747bfb-ec96-4170-9ed0-3bb96c3fe1f5.jpg)

**Comment by osuleymanova** [comment]
@muhammad-farhan-bakht 
Thank you for reaching out to us. The issue is fixed and published.
