### ISSUE TITLE
Android Basics: Coroutines - is runBlocking() suspend or not?

### ISSUE THREAD

**Issue by RichardBenes** [google-developer-training/android-basics-kotlin-mars-photos-app#9]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-introduction-coroutines?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-introduction-coroutines#3

**In which task and step of the codelab can this issue be found?**
Coroutines in Kotlin

**Describe the problem**

Last paragraph states:

Not necessarily. getValue() is actually called in the function passed **into runBlocking(), which is a suspend function**, similar to the ones passed into launch() and async(). However, getValue() is not called in main() itself, **nor is runBlocking() a suspend function**, so main() is not marked with suspend. If a function does not call a suspend function, then it does not need to be a suspend function itself.

Hello, I'm confused by this - does this paragraph want to say that runBlocking() is or is not a suspend function?

Best regards,
Richard Beneš

**Comment by osuleymanova** [comment]
@RichardBenes 
The issue that you presented to us is extremely important, and I thank you for bringing your concern to our attention. The codelab content was updated and will be published soon.
![Screen Shot 2022-04-15 at 11 55 20 AM](https://user-images.githubusercontent.com/86437155/163617256-d35e2554-66b1-4cc3-9206-1e43c5082821.png)
Hope it clarifies better!
